In [128]:
import numpy as np

### valid sudoku

In [129]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 4],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [130]:
b = np.sum(s, axis=1)

for i in b:
    if i != 45:
        print("Sudoko is not valid")
        break
else:
    print("For rows sudoku is valid")

Sudoko is not valid


In [131]:
c = np.sum(s, axis=0)

for i in c:
    if i != 45:
        print("Sudoku is not valid")
        break
else:
    print("For colums sudoku is valid")

Sudoku is not valid


In [132]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        n = s[i:i+3, j:j+3]
        print(n.sum())

45
45
47
45
45
45
45
45
45


### Genreal Questions

In [133]:
# Columns: [Age, Math marks, Science marks]
data = np.array([
    [18, 85, 78], # student 1
    [19, 92, 88], # student 2
    [17, 76, 95], # student 3
    [18, 65, 70], # student 4
    [20, 90, 85]  # student 5
])

In [134]:
# get the shape of the matrix

print(data.shape)

(5, 3)


In [135]:
# find the average age of students

print(np.mean(data[:,0]))

18.4


In [136]:
# extract math marks fo all students

print(data[:,1])

[85 92 76 65 90]


In [137]:
# find the highest science marks

print(np.max(data[:,2]))

95


In [138]:
# get details of the student who scored more than 90 in math

math_marks_more_than_90 = data[data[:,1] > 90]
print(math_marks_more_than_90)

[[19 92 88]]


In [139]:
# increase math marks of all students by 5

data[:,1] += 5

print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


In [140]:
# find how many students are younger than 19

len(data[data[:,0] < 19])

3

In [141]:
# calculate the average marks in each subject (column-wise mean)

np.mean(data[:,1:], axis=0)

array([86.6, 83.2])

In [142]:
# get data of students who scored at least 80 in both subjects

data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [143]:
# replace all science marks < 75 with 0

data[:,2][data[:,2] < 75] = 0

In [144]:
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70  0]
 [20 95 85]]
