### Origin story of numpy

python was always very powerful with maths but one thing was missing that was arrays to 
solve this thing there was a creater named as James Hugunin in 1995 and he created a numeric
library. This library provided array support but the problem was the performance was not 
that good and thing thing was further resolved in early 2000's another library was developed
by Space Telescope Science Intitute and named it numarray to increase the power of previously
created library but it was not compatible with numeric library

After that in 2005 there was a professor and scientist named as Travis Oliphant who merged
numeric and numarray and named it Numpy and finally there was library named as numpy

It was made in C thats why it is 50x faster than python list

### Numpy features
    - Data Type: Same data type only
    - Performance: Much faster (c-level)
    - Memory efficency: High
    - Vector operations: Easy + fast

In [4]:
import numpy as np

### Basic Array Creation

In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

In [6]:
mat = np.array([[1, 2, 4], [4, 5, 6], [7, 8, 9]])
mat

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

### Array Genration Fuctions

In [7]:
arr = np.arange(1, 11)
arr
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [8]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [9]:
arr = np.zeros((2, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [11]:
arr = np.ones((2, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr = np.linspace(1, 5, 3)
arr

array([1., 3., 5.])

### Random Genration Functions

In [13]:
arr = np.random.rand(10)
arr

array([0.83454142, 0.94618305, 0.20661338, 0.80506375, 0.38576799,
       0.25842373, 0.43226475, 0.10025402, 0.22005073, 0.49238993])

In [14]:
arr = np.random.randn(10)
arr

array([-1.06106863, -2.2065453 ,  1.0080207 , -0.65391649,  0.18081543,
        0.30633888, -0.98271354,  1.2917476 ,  0.54736528,  0.06850873])

In [15]:
arr = np.random.randint(10, 20, 10)
arr

array([13, 14, 18, 19, 16, 14, 11, 17, 14, 14])

### Array Attributes

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.shape

(3, 3)

In [18]:
arr.size

9

In [19]:
arr.dtype

dtype('int64')

### Array Methods

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.min()

np.int64(1)

In [22]:
arr.max()

np.int64(9)

In [23]:
arr.sum()

np.int64(45)

In [24]:
# axis = 0 (y - axis)
# axis = 1 (x - axis)
np.sum(arr, axis = 0)

array([12, 15, 18])

In [25]:
arr.mean()

np.float64(5.0)

In [26]:
arr.std()

np.float64(2.581988897471611)

In [27]:
arr.argmax() # index of maximum element

np.int64(8)

In [28]:
arr.argmin() # index of minimum element

np.int64(0)

### Reshaping and Resizing

In [29]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [30]:
# converting into matrix
arr = arr.reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [31]:
resized = np.resize(arr, (9, 10))
resized

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

## Section 2

### Numpy Indexing and Slicing of vectors

In [32]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
print(arr[6])

17


In [34]:
print(arr[1:5])

[12 13 14 15]


In [35]:
print(arr[:5])

[11 12 13 14 15]


In [36]:
print(arr[:])

[11 12 13 14 15 16 17 18 19 20]


In [37]:
print(arr[3:])

[14 15 16 17 18 19 20]


In [38]:
print(arr[3::2])

[14 16 18 20]


### Numpy Indexing and Slicing of Matrix

In [39]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [40]:
print(arr[5]) # it will target rows

[26 27 28 29 30]


In [41]:
print(arr[5, 3]) # first number will target rows and second number will target columns

29


In [42]:
print(arr[0:2, 1:3])

[[2 3]
 [7 8]]


In [43]:
print(arr[3:, 3:])

[[19 20]
 [24 25]
 [29 30]]


In [44]:
print(arr[:, 2]) # indexing a column

[ 3  8 13 18 23 28]


### Boolean Indexing

In [45]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [47]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

## Section 3

### Array Operations

### Arithmetic Operations

In [48]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [49]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [50]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [51]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [52]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [53]:
a1 // a2

array([0, 0, 0, 0, 0])

In [54]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [56]:
a1 % a2

array([1, 2, 3, 4, 5])

### Broadcasting

In [57]:
l = [10, 20, 30, 40]
arr = np.array(l)

In [59]:
arr + 10

array([20, 30, 40, 50])

In [61]:
arr2 = np.arange(1, 26).reshape(5, 5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [62]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

### Deep and Shallow Copy

In [63]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# shallow copy - main array doesn't changes
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [68]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [69]:
a[4:6] * 10

array([50, 60])

In [70]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Matrix Operations

In [71]:
A = np.array([[1, 2], [3, 4]])
B  = np.array([[5, 6], [7, 8]])

In [72]:
A

array([[1, 2],
       [3, 4]])

In [73]:
B

array([[5, 6],
       [7, 8]])

In [75]:
A @ B # matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A, B) # dot product of matrix

array([[19, 22],
       [43, 50]])

In [ ]:
np.transpose(A) # transpose of matrix

array([[1, 3],
       [2, 4]])

### Advanced Array Manipulation (Stacking array and Splitting array)

### Stacking Array: We cannot stack two matrix we always need 1D array

In [81]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [83]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [84]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Splitting Array

In [87]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [90]:
np.hsplit(c, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [91]:
np.vsplit(c, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [92]:
np.vsplit(c, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [94]:
for i in c:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
